name: CI - Test and Lint

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop

jobs:
  test-api:
    name: Test API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run type check
        run: bun run typecheck

      - name: Run linter
        run: bun run lint

      - name: Run tests
        run: bun test
        env:
          NODE_ENV: test
          DATABASE_URL: postgresql://test:test@localhost:5432/test

  test-ui:
    name: Test UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run type check
        run: bun tsc --noEmit

      - name: Run linter
        run: bun run lint

      - name: Run tests
        run: bun test
        env:
          NODE_ENV: test

      - name: Build application
        run: bun run build
        env:
          VITE_API_URL: /api
          VITE_APP_ENV: test

  docker-build-test:
    name: Test Docker Builds
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          push: false
          tags: gg-mvp-api:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build UI Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/ui
          file: ./apps/ui/Dockerfile
          push: false
          tags: gg-mvp-ui:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_API_URL=/api
            VITE_APP_ENV=test