version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: goldengate-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: goldengate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/db/init:/docker-entrypoint-initdb.d
    networks:
      - goldengate-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d goldengate"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres-test:
    image: postgres:16-alpine
    container_name: goldengate-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: goldengate_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./api/db/init:/docker-entrypoint-initdb.d
    networks:
      - goldengate-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d goldengate_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: goldengate-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - goldengate-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1
    container_name: goldengate-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - goldengate-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha

volumes:
  postgres_data:
    driver: local
  postgres_test_data:
    driver: local
  redis_data:
    driver: local

networks:
  goldengate-network:
    driver: bridge